var searchData=
[
  ['onglet_5fson_0',['ONGLET_SON',['../fonctions__generales_8h.html#a51597df745ec0491d186d1901b3bb364a2e98a954ec1b0246c867b436c6341b3b',1,'fonctions_generales.h']]],
  ['onglet_5ftouches_1',['ONGLET_TOUCHES',['../fonctions__generales_8h.html#a51597df745ec0491d186d1901b3bb364a7b77d5982c5312b395828ad434f8df7f',1,'fonctions_generales.h']]],
  ['option_5fs_2',['option_s',['../fonctions__generales_8h.html#a51597df745ec0491d186d1901b3bb364',1,'fonctions_generales.h']]],
  ['option_5ft_3',['option_t',['../fonctions__generales_8h.html#a0326ccf9b7f34b705de9ab12ff062beb',1,'fonctions_generales.h']]],
  ['options_4',['OPTIONS',['../fonctions__generales_8h.html#a2cbae93ea482503b066433625257cfa3a1b20f1b4adb6ff9778b284fb46f6f99d',1,'fonctions_generales.h']]],
  ['options_5',['options',['../fonctions__options_8c.html#a8bdd9c80ba51365b04256e860b3b8801',1,'options(SDL_Event *event, SDL_Window **window, SDL_Renderer **renderer, SDL_bool *programme_lance, SDL_Rect *rectangle_plein_ecran, SDL_Texture **texture_image_plein_ecran, SDL_bool *plein_ecran, SDL_Rect *rectangle_retour_en_arriere, SDL_Texture **texture_image_retour_en_arriere, SDL_Texture **texture_image_hautParleurActif, SDL_Rect *rectangle_demande_sauvegarde, itemMenu *itemsDemandeSauvegarde, int tailleDemandeSauvegarde, SDL_Texture **texture_image_hautParleurDesactive, SDL_bool *sonsActifs, SDL_Rect *rectangles_boutons_sons, option_t *ongletActif, itemMenu *pseudo, modes_t *modeActif, personnage_t *personnageActif, position_t *positionActive, niveaux *avancee_niveaux, int tailleNiveaux, itemMenu *titre, SDL_Surface **surface, SDL_Texture **texture_texte, TTF_Font **police, int *selection_touche, SDL_Keycode *touche_aller_a_droite, SDL_Keycode *touche_aller_a_gauche, SDL_Keycode *touche_sauter_monter, SDL_Keycode *touche_descendre, SDL_Keycode *touche_interagir, SDL_Color couleurNoire, itemMenu *itemsMenu, int tailleMenu, itemMenu *itemsTouches, int tailleTouches, barreDeSon *barre_de_son, int tailleBarres, itemMenu *itemsBarres, int *largeur, int *hauteur, page_t *page_active, page_t *page_precedente, int *maintient_clic, time_t temps_debut_partie, int *compteur_mort, int *avancee_succes):&#160;fonctions_options.c'],['../fonctions__options_8h.html#a8bdd9c80ba51365b04256e860b3b8801',1,'options(SDL_Event *event, SDL_Window **window, SDL_Renderer **renderer, SDL_bool *programme_lance, SDL_Rect *rectangle_plein_ecran, SDL_Texture **texture_image_plein_ecran, SDL_bool *plein_ecran, SDL_Rect *rectangle_retour_en_arriere, SDL_Texture **texture_image_retour_en_arriere, SDL_Texture **texture_image_hautParleurActif, SDL_Rect *rectangle_demande_sauvegarde, itemMenu *itemsDemandeSauvegarde, int tailleDemandeSauvegarde, SDL_Texture **texture_image_hautParleurDesactive, SDL_bool *sonsActifs, SDL_Rect *rectangles_boutons_sons, option_t *ongletActif, itemMenu *pseudo, modes_t *modeActif, personnage_t *personnageActif, position_t *positionActive, niveaux *avancee_niveaux, int tailleNiveaux, itemMenu *titre, SDL_Surface **surface, SDL_Texture **texture_texte, TTF_Font **police, int *selection_touche, SDL_Keycode *touche_aller_a_droite, SDL_Keycode *touche_aller_a_gauche, SDL_Keycode *touche_sauter_monter, SDL_Keycode *touche_descendre, SDL_Keycode *touche_interagir, SDL_Color couleurNoire, itemMenu *itemsMenu, int tailleMenu, itemMenu *itemsTouches, int tailleTouches, barreDeSon *barre_de_son, int tailleBarres, itemMenu *itemsBarres, int *largeur, int *hauteur, page_t *page_active, page_t *page_precedente, int *maintient_clic, time_t temps_debut_partie, int *compteur_mort, int *avancee_succes):&#160;fonctions_options.c']]]
];
